// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: client_common_msg.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerResRouterMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] msgContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerErrorMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Info { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum ErrorType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OK")]
            Ok = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR")]
            Error = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BUSY")]
            Busy = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"NO_ACTIVATION")]
            NoActivation = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"NO_OPEN_SERVER")]
            NoOpenServer = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActivationCardMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Info { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum ErrorType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OK")]
            Ok = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR")]
            Error = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BUSY")]
            Busy = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"NULL_PFID")]
            NullPfid = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_PFID")]
            ErrorPfid = -3,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
