// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: client_proxy_msg.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientRouterMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string serviceName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"userid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Userid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string channlId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public byte[] msgContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientAuthMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"userid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Userid { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ParameterMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string userId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string channelId { get; set; } = "";

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
